const fs=require('node:fs'),assert=require('node:assert/strict');
const html=fs.readFileSync('dist/index.html','utf8');
const js=fs.readFileSync('dist/js/accidents.js','utf8');
const css=fs.readFileSync('dist/css/app.css','utf8');
const auth=fs.readFileSync('dist/js/supabase-auth.js','utf8');
const app=fs.readFileSync('dist/js/app.js','utf8');
const sql=fs.readFileSync('supabase/014_vehicle_accidents.sql','utf8');
const pdfSql=fs.readFileSync('supabase/015_accident_pdf_attachments.sql','utf8');
const replacementSql=fs.readFileSync('supabase/016_accident_replacement_vehicle.sql','utf8');
const authorSql=fs.readFileSync('supabase/017_author_manage_accidents_handovers.sql','utf8');
assert(html.includes('data-page="사고접수 및 이력"'));
['accidentView','accidentVehicle','accidentDate','accidentPassengers','accidentReplacementVehicle','accidentLocation','accidentDescription','accidentPhotos','accidentRows'].forEach(id=>assert(html.includes(`id="${id}"`)));
assert(html.includes('id="accidentVehicle" type="search"'));
assert(html.includes('id="accidentVehicleSuggestions"'));
assert(js.includes("vehicleForPlate(el('accidentVehicle').value)"));
assert(js.includes('matchingAccidentVehicles'));
assert(js.includes('data-accident-vehicle'));
assert(js.includes("담당(정) ${vehicle['담당자(정)']||'미지정'} · 담당(부) ${vehicle['담당자(부)']||'미지정'}"));
assert(js.includes("from('vehicle_accidents').insert"));
assert(js.includes("from('accident-photos').upload"));
assert(js.includes('replacement_vehicle_number'));
assert(js.includes('data-accident-detail-close'));
assert(js.includes('data-accident-row'));
assert(js.includes("detailRow.className='inline-detail-row'"));
assert(!html.includes('id="accidentDetail"'));
assert(js.includes("rowsEl.addEventListener('submit'"));
assert(js.includes('created_by===window.fleetCurrentUser?.id'));
assert(js.includes('data-accident-edit'));
assert(js.includes("photos.length>3"));
assert(js.includes("'application/pdf'"));
assert(html.includes('accept="image/jpeg,image/png,image/webp,application/pdf,.pdf"'));
assert(js.includes("rpc('comment_vehicle_accident'"));
assert(css.includes('.handover-detail .attachment-pdf') && css.includes('height: 78px'));
assert(auth.includes("'사고접수 및 이력'"));
assert(app.includes("button.dataset.page === '사고접수 및 이력'"));
['create table if not exists public.vehicle_accidents','create or replace function public.comment_vehicle_accident','accident-photos','vehicle_accidents_insert_active',"current_user_role()<>'admin'"].forEach(value=>assert(sql.includes(value)));
assert(pdfSql.includes("'application/pdf'"));
assert(replacementSql.includes('replacement_vehicle_number'));
assert(authorSql.includes('vehicle_accidents_update_author_or_admin'));
console.log('PASS: accident menu, vehicle snapshot, photo upload, admin comment UI, and SQL access rules (static).');
