const fs = require('node:fs');
const assert = require('node:assert/strict');
const html = fs.readFileSync('dist/index.html', 'utf8');
const dashboard = html.split('id="dashboardView"')[1].split('id="vehiclesView"')[0];
const titles = ['전체 운영 차량', '렌트 계약금액', '6개월 내 계약 만료 예정 차량', '부서별 차량 현황', '차량이용량(팀)', '월별 차량 부대비용 추이'];
const metrics = dashboard.split('class="metrics"')[1].split('</section>')[0];
assert(metrics.includes('id="dashboardExpiryCount"'));
assert(metrics.includes('id="dashboardVehiclesShortcut"'));
assert(metrics.includes('id="dashboardContractAmountShortcut"'));
assert(metrics.includes('id="allVehiclesButton"'));
assert(!metrics.includes('metric-icon'));
assert(!metrics.includes('<svg viewBox="0 0 24 24"'));
assert(!dashboard.includes('현재 저장정보 현황'));
assert(!dashboard.includes('렌터카 자료를 기준으로 주요 운영 현황과 비용을 요약했습니다.'));
assert(!dashboard.includes('reportButton'));
assert(!dashboard.includes('보고서 인쇄'));
const css = fs.readFileSync('dist/css/app.css', 'utf8');
const js = fs.readFileSync('dist/js/app.js', 'utf8');
assert(!/\.department-overview \.department-list\s*\{[^}]*(max-height|overflow-y)/.test(css));
const positions = titles.map(title => dashboard.indexOf(title));
assert(positions.every((position, index) => position >= 0 && (!index || position > positions[index - 1])));
assert.equal((dashboard.match(/id="dashboardUsageMonth"/g) || []).length, 1);
assert.equal((dashboard.match(/id="costTrendReferenceMonth"/g) || []).length, 1);
assert.equal((dashboard.match(/id="costTrendPeriodMonths"/g) || []).length, 1);
assert(!dashboard.includes('class="panel cost-panel"'));
assert(dashboard.includes('id="dashboardUsageDaysHigh"'));
assert(dashboard.includes('id="dashboardUsageDaysLow"'));
assert(dashboard.includes('id="dashboardUsageDistanceHigh"'));
assert(dashboard.includes('id="dashboardUsageDistanceLow"'));
assert((dashboard.match(/<th>차량번호<\/th><th>팀<\/th>/g) || []).length === 4);
assert(!dashboard.includes('dashboardUsageStatus'));
assert(!dashboard.includes('확정월의 차량번호별 기록을 합산합니다.'));
assert(!dashboard.includes('차량별 서로 다른 운행 날짜 수'));
assert(!dashboard.includes('차량별 해당 월 이동거리 합계'));
assert.equal((dashboard.match(/<h4>상위<\/h4>/g) || []).length, 2);
assert.equal((dashboard.match(/<h4>하위<\/h4>/g) || []).length, 2);
assert(!dashboard.includes('많은 차량'));
assert(!dashboard.includes('적은 차량'));
assert(css.includes('.usage-ranking-tables > div + div'), 'upper/lower ranking separation styling is missing');
assert(!js.includes("getElementById('reportButton')"), 'removed report button still has an event handler');
assert(js.includes("getElementById('dashboardVehiclesShortcut')?.addEventListener('click', () => showView('차량 현황'"), 'vehicle dashboard shortcut is missing');
assert(js.includes("getElementById('dashboardContractAmountShortcut')?.addEventListener('click', () => showView('차량계약정보'"), 'contract amount dashboard shortcut is missing');
assert(js.includes("const month=document.getElementById('dashboardUsageMonth').value,item=drivingArchive[month];"), 'usage ranking must retain its selected month archive lookup');
console.log('PASS: dashboard section order and month controls (HTML, no visual browser check).');
