const fs=require('node:fs'),assert=require('node:assert/strict');
const html=fs.readFileSync('dist/index.html','utf8');
const js=fs.readFileSync('dist/js/knowledge.js','utf8');
const auth=fs.readFileSync('dist/js/supabase-auth.js','utf8');
const sql=fs.readFileSync('supabase/011_knowledge_center.sql','utf8');
const answerDatesSql=fs.readFileSync('supabase/025_qna_answer_dates.sql','utf8');

for(const id of ['qnaView','guideView','qnaForm','qnaRows','qnaPagination','guideForm','guideRows','guidePagination']) assert(html.includes(`id="${id}"`),`missing ${id}`);
assert(html.includes('data-page="Q&A"'));
assert(html.includes('data-page="운행가이드"'));
for(const text of ['fleet_questions','fleet_guides','fleet-guides','createSignedUrl','storage.from(\'fleet-guides\').download','20 * 1024 * 1024']) assert(js.includes(text),`missing knowledge code: ${text}`);
assert(auth.includes("new Set(['차량 현황','사고접수 및 이력','차량인수인계','Q&A','운행가이드'])"), 'viewer Q&A/guide navigation is missing');
assert(js.includes("el('qnaAdminPanel').hidden = !isAdmin()"), 'Q&A admin panel restriction is missing');
assert(js.includes("el('guideAdminPanel').hidden = !isAdmin()"), 'guide admin panel restriction is missing');
assert(js.includes('<strong>Q:</strong>'), 'Q&A question prefix is missing');
assert(js.includes('<strong>A:</strong>'), 'Q&A answer prefix is missing');
assert(!js.includes('답변 등록일 ${displayDate(item.answered_at || item.created_at)}'), 'Q&A answer date must not be displayed');
assert(js.includes('const knowledgePageSize = 20'), 'knowledge list page size is missing');
assert(js.includes("renderKnowledgePagination('qnaPagination'"), 'Q&A pagination is missing');
assert(js.includes("renderKnowledgePagination('guidePagination'"), 'guide pagination is missing');
for(const text of ['create table if not exists public.fleet_questions','create table if not exists public.fleet_guides',"'fleet-guides'","array['application/pdf']",'fleet_questions_manage_admin','fleet_guides_manage_admin','fleet_guides_storage_read_active','fleet_guides_storage_insert_admin','fleet_guides_storage_delete_admin']) assert(sql.includes(text),`missing knowledge SQL: ${text}`);
for(const text of ['add column if not exists answered_at timestamptz','set answered_at = created_at where answered_at is null','new.answer_body is distinct from old.answer_body']) assert(answerDatesSql.includes(text),`missing Q&A answer date rule: ${text}`);
console.log('PASS: Q&A and PDF guide UI, admin restrictions and SQL policy wiring (static).');
